/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import javax.swing.JOptionPane;

public class GuiAluno extends javax.swing.JFrame {


    /**
     * Creates new form GuiAluno
     */
    public GuiAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtInserir = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();
        LbCPF = new javax.swing.JLabel();
        CbSexo = new javax.swing.JComboBox<>();
        LbNome = new javax.swing.JLabel();
        TfNome = new javax.swing.JTextField();
        LbSexo = new javax.swing.JLabel();
        CbEstadoCivil = new javax.swing.JComboBox<>();
        LbEstadoCivil = new javax.swing.JLabel();
        LbEndereco = new javax.swing.JLabel();
        TfEndereco = new javax.swing.JTextField();
        LbEscolaridade = new javax.swing.JLabel();
        CbEscolaridade = new javax.swing.JComboBox<>();
        LbDataNascto = new javax.swing.JLabel();
        LbBairro = new javax.swing.JLabel();
        TfBairro = new javax.swing.JTextField();
        LbCidade = new javax.swing.JLabel();
        TfCidade = new javax.swing.JTextField();
        LbRG = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        TfEmail = new javax.swing.JTextField();
        LbEstado = new javax.swing.JLabel();
        CbEstado = new javax.swing.JComboBox<>();
        TfNumero = new javax.swing.JTextField();
        LbNumero = new javax.swing.JLabel();
        LbCEP = new javax.swing.JLabel();
        LbTelRes = new javax.swing.JLabel();
        LbCelular = new javax.swing.JLabel();
        FtfDataNascto = new javax.swing.JFormattedTextField();
        FtfCPF = new javax.swing.JFormattedTextField();
        FtfRG = new javax.swing.JFormattedTextField();
        FtfTelRes = new javax.swing.JFormattedTextField();
        FtfCelular = new javax.swing.JFormattedTextField();
        FtfCEP = new javax.swing.JFormattedTextField();

        setTitle("Cadastrar Aluno");
        setName("FrameCadastrarAluno"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.setEnabled(false);
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.setEnabled(false);
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        BtInserir.setText("Inserir");
        BtInserir.setEnabled(false);
        BtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInserirActionPerformed(evt);
            }
        });

        BtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        BtSair.setText("Sair");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        BtConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        BtConsultar.setText("Consultar");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        LbCPF.setText("CPF");

        CbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        CbSexo.setSelectedIndex(-1);
        CbSexo.setEnabled(false);

        LbNome.setText("Nome");

        TfNome.setEnabled(false);

        LbSexo.setText("Sexo");

        CbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado" }));
        CbEstadoCivil.setSelectedIndex(-1);
        CbEstadoCivil.setEnabled(false);

        LbEstadoCivil.setText("Estado Civil");

        LbEndereco.setText("Endereço");

        TfEndereco.setEnabled(false);

        LbEscolaridade.setText("Escolaridade");

        CbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Médio", "Graduação", "Mestrado" }));
        CbEscolaridade.setSelectedIndex(-1);
        CbEscolaridade.setEnabled(false);

        LbDataNascto.setText("Data Nascto");

        LbBairro.setText("Bairro");

        TfBairro.setEnabled(false);

        LbCidade.setText("Cidade");

        TfCidade.setEnabled(false);

        LbRG.setText("RG");

        LbEmail.setText("Email");

        TfEmail.setEnabled(false);

        LbEstado.setText("Estado");

        CbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        CbEstado.setSelectedIndex(-1);
        CbEstado.setEnabled(false);

        TfNumero.setEnabled(false);

        LbNumero.setText("Nº");

        LbCEP.setText("CEP");

        LbTelRes.setText("Tel. Res");

        LbCelular.setText("Celular");

        try {
            FtfDataNascto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfDataNascto.setEnabled(false);

        try {
            FtfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FtfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfRG.setEnabled(false);

        try {
            FtfTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfTelRes.setEnabled(false);

        try {
            FtfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfCelular.setEnabled(false);

        try {
            FtfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfCEP.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbRG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbCidade, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TfBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TfEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TfCidade)
                                            .addComponent(FtfRG, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(LbEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(LbCEP)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(FtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(LbTelRes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(FtfTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LbCelular)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(FtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LbEstadoCivil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbEscolaridade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbDataNascto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FtfDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LbCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEndereco)
                    .addComponent(LbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbBairro)
                    .addComponent(LbCEP)
                    .addComponent(FtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCidade)
                    .addComponent(LbTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRG)
                    .addComponent(LbCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtInserir)
                    .addComponent(BtConsultar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir)
                    .addComponent(BtSair))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        BtAlterar.getAccessibleContext().setAccessibleName("Botão Alterar");
        BtExcluir.getAccessibleContext().setAccessibleName("Botão Excluir");
        BtInserir.getAccessibleContext().setAccessibleName("Botão Inserir");
        BtSair.getAccessibleContext().setAccessibleName("Botão Sair");
        BtConsultar.getAccessibleContext().setAccessibleName("Botão Consultar");
        CbSexo.getAccessibleContext().setAccessibleName("Sexo");
        TfNome.getAccessibleContext().setAccessibleName("Nome");
        CbEstadoCivil.getAccessibleContext().setAccessibleName("Estado Civil");
        TfEndereco.getAccessibleContext().setAccessibleName("Endereço");
        CbEscolaridade.getAccessibleContext().setAccessibleName("Escolaridade");
        TfBairro.getAccessibleContext().setAccessibleName("Bairro");
        TfCidade.getAccessibleContext().setAccessibleName("Cidade");
        TfEmail.getAccessibleContext().setAccessibleName("Email");
        CbEstado.getAccessibleContext().setAccessibleName("Estado");
        TfNumero.getAccessibleContext().setAccessibleName("Número");
        FtfDataNascto.getAccessibleContext().setAccessibleName("Data de Nascimento");
        FtfCPF.getAccessibleContext().setAccessibleName("CPF");
        FtfRG.getAccessibleContext().setAccessibleName("RG");
        FtfTelRes.getAccessibleContext().setAccessibleName("Tel Residencial");
        FtfCelular.getAccessibleContext().setAccessibleName("Celular");
        FtfCEP.getAccessibleContext().setAccessibleName("CEP");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("chris","goku");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoAluno = new DaoAluno(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        aluno = null;
        aluno = daoAluno.consultar(FtfCPF.getText());
        if (aluno == null) {
            FtfCPF.setEnabled(false);
            CbSexo.setEnabled(true);
            CbEstadoCivil.setEnabled(true);
            CbEscolaridade.setEnabled(true);
            CbEstado.setEnabled(true);
            FtfDataNascto.setEnabled(true);
            FtfCEP.setEnabled(true);
            FtfTelRes.setEnabled(true);
            FtfRG.setEnabled(true);
            FtfCelular.setEnabled(true);
            TfNome.setEnabled(true);
            TfEndereco.setEnabled(true);
            TfNumero.setEnabled(true);
            TfBairro.setEnabled(true);
            TfCidade.setEnabled(true);
            TfEmail.setEnabled(true);
                       
            BtConsultar.setEnabled(false);
            BtInserir.setEnabled(true);
            BtAlterar.setEnabled(false);
            BtExcluir.setEnabled(false);
            
            TfNome.requestFocus();
        } else {
            CbSexo.setSelectedItem(aluno.getSexo());
            CbEstadoCivil.setSelectedItem(aluno.getEstadoCivil());
            CbEscolaridade.setSelectedItem(aluno.getEscolaridade());
            CbEstado.setSelectedItem(aluno.getEstado());
            FtfDataNascto.setText(aluno.getDataNasc());
            FtfCEP.setText(aluno.getCEP());
            FtfTelRes.setText(aluno.getTelefone());
            FtfRG.setText(aluno.getRG());
            FtfCelular.setText(aluno.getCelular());
            TfNome.setText(aluno.getNome());
            TfEndereco.setText(aluno.getEndereco());
            TfNumero.setText(Integer.toString(aluno.getNumero()));
            TfBairro.setText(aluno.getBairro());
            TfCidade.setText(aluno.getCidade());
            TfEmail.setText(aluno.getEmail());
            
            FtfCPF.setEnabled(false); 
            CbSexo.setEnabled(true);
            CbEstadoCivil.setEnabled(true);
            CbEscolaridade.setEnabled(true);
            CbEstado.setEnabled(true);
            FtfDataNascto.setEnabled(true);
            FtfCEP.setEnabled(true);
            FtfTelRes.setEnabled(true);
            FtfRG.setEnabled(true);
            FtfCelular.setEnabled(true);
            TfNome.setEnabled(true);        
            TfEndereco.setEnabled(true);
            TfNumero.setEnabled(true);
            TfBairro.setEnabled(true);
            TfCidade.setEnabled(true);
            TfEmail.setEnabled(true);

            BtConsultar.setEnabled(false);
            BtInserir.setEnabled(false);
            BtAlterar.setEnabled(true);
            BtExcluir.setEnabled(true);
            
            TfNome.requestFocus();    
        }    
    }//GEN-LAST:event_BtConsultarActionPerformed

    private void BtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInserirActionPerformed
        aluno = new Aluno(FtfCPF.getText(), TfNome.getText());
        
        aluno.setSexo(String.valueOf(CbSexo.getSelectedItem()));
        aluno.setEstadoCivil(String.valueOf(CbEstadoCivil.getSelectedItem()));
        aluno.setEscolaridade(String.valueOf(CbEscolaridade.getSelectedItem()));
        aluno.setEstado(String.valueOf(CbEstado.getSelectedItem()));
        aluno.setDataNasc(FtfDataNascto.getText());
        aluno.setCEP(FtfCEP.getText());
        aluno.setTelefone(FtfTelRes.getText());
        aluno.setRG(FtfRG.getText());
        aluno.setCelular(FtfCelular.getText());
        aluno.setEndereco(TfEndereco.getText());
        aluno.setNumero(Integer.valueOf(TfNumero.getText()));
        aluno.setBairro(TfBairro.getText());
        aluno.setCidade(TfCidade.getText());
        aluno.setEmail(TfEmail.getText());
        
        daoAluno.inserir(aluno);
        
        FtfCPF.setText("");
        CbSexo.setSelectedItem(-1);
        CbEstadoCivil.setSelectedItem(-1);
        CbEscolaridade.setSelectedItem(-1);
        CbEstado.setSelectedItem(-1);
        FtfDataNascto.setText("");
        FtfCEP.setText("");
        FtfTelRes.setText("");
        FtfRG.setText("");
        FtfCelular.setText("");
        TfNome.setText("");
        TfEndereco.setText("");
        TfNumero.setText("");
        TfBairro.setText("");
        TfCidade.setText("");
        TfEmail.setText("");
        
        
        FtfCPF.setEnabled(true);
        CbSexo.setEnabled(false);
        CbEstadoCivil.setEnabled(false);
        CbEscolaridade.setEnabled(false);
        CbEstado.setEnabled(false); 
        FtfDataNascto.setEnabled(false);
        FtfCEP.setEnabled(false);
        FtfTelRes.setEnabled(false);
        FtfRG.setEnabled(false);
        FtfCelular.setEnabled(false);
        TfNome.setEnabled(false);        
        TfEndereco.setEnabled(false);
        TfNumero.setEnabled(false);
        TfBairro.setEnabled(false);
        TfCidade.setEnabled(false);
        TfEmail.setEnabled(false);
        
        BtConsultar.setEnabled(true);
        BtInserir.setEnabled(false);
        
        FtfCPF.requestFocus();
    }//GEN-LAST:event_BtInserirActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0) {
            aluno.setNome(TfNome.getText());
            aluno.setSexo(String.valueOf(CbSexo.getSelectedItem()));
            aluno.setEstadoCivil(String.valueOf(CbEstadoCivil.getSelectedItem()));
            aluno.setEscolaridade(String.valueOf(CbEscolaridade.getSelectedItem()));
            aluno.setEstado(String.valueOf(CbEstado.getSelectedItem()));
            aluno.setDataNasc(FtfDataNascto.getText());
            aluno.setCEP(FtfCEP.getText());
            aluno.setTelefone(FtfTelRes.getText());
            aluno.setRG(FtfRG.getText());
            aluno.setCelular(FtfCelular.getText());
            aluno.setEndereco(TfEndereco.getText());
            aluno.setNumero(Integer.valueOf(TfNumero.getText()));
            aluno.setBairro(TfBairro.getText());
            aluno.setCidade(TfCidade.getText());
            aluno.setEmail(TfEmail.getText());
            daoAluno.alterar(aluno);
        } 
        
        FtfCPF.setText("");
        CbSexo.setSelectedItem(-1);
        CbEstadoCivil.setSelectedItem(-1);
        CbEscolaridade.setSelectedItem(-1);
        CbEstado.setSelectedItem(-1);
        FtfDataNascto.setText("");
        FtfCEP.setText("");
        FtfTelRes.setText("");
        FtfRG.setText("");
        FtfCelular.setText("");
        TfNome.setText("");
        TfEndereco.setText("");
        TfNumero.setText("");
        TfBairro.setText("");
        TfCidade.setText("");
        TfEmail.setText("");
        
        FtfCPF.setEnabled(true);
        CbSexo.setEnabled(false);
        CbEstadoCivil.setEnabled(false);
        CbEscolaridade.setEnabled(false);
        CbEstado.setEnabled(false); 
        FtfDataNascto.setEnabled(false);
        FtfCEP.setEnabled(false);
        FtfTelRes.setEnabled(false);
        FtfRG.setEnabled(false);
        FtfCelular.setEnabled(false);
        TfNome.setEnabled(false);        
        TfEndereco.setEnabled(false);
        TfNumero.setEnabled(false);
        TfBairro.setEnabled(false);
        TfCidade.setEnabled(false);
        TfEmail.setEnabled(false);
        
        BtConsultar.setEnabled(true);
        BtInserir.setEnabled(false);
        BtAlterar.setEnabled(false);
        BtExcluir.setEnabled(false);
        
        FtfCPF.requestFocus();
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            daoAluno.excluir(aluno); 

            FtfCPF.setText("");
            CbSexo.setSelectedItem(-1);
            CbEstadoCivil.setSelectedItem(-1);
            CbEscolaridade.setSelectedItem(-1);
            CbEstado.setSelectedItem(-1);
            FtfDataNascto.setText("");
            FtfCEP.setText("");
            FtfTelRes.setText("");
            FtfRG.setText("");
            FtfCelular.setText("");
            TfNome.setText("");
            TfEndereco.setText("");
            TfNumero.setText("");
            TfBairro.setText("");
            TfCidade.setText("");
            TfEmail.setText("");

            FtfCPF.setEnabled(true);
            CbSexo.setEnabled(false);
            CbEstadoCivil.setEnabled(false);
            CbEscolaridade.setEnabled(false);
            CbEstado.setEnabled(false); 
            FtfDataNascto.setEnabled(false);
            FtfCEP.setEnabled(false);
            FtfTelRes.setEnabled(false);
            FtfRG.setEnabled(false);
            FtfCelular.setEnabled(false);
            TfNome.setEnabled(false);        
            TfEndereco.setEnabled(false);
            TfNumero.setEnabled(false);
            TfBairro.setEnabled(false);
            TfCidade.setEnabled(false);
            TfEmail.setEnabled(false);

            BtConsultar.setEnabled(true);
            BtInserir.setEnabled(false);
            BtAlterar.setEnabled(false);
            BtExcluir.setEnabled(false);

            FtfCPF.requestFocus();
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        dispose();
    }//GEN-LAST:event_BtSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        conexao.fecharConexao();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtInserir;
    private javax.swing.JButton BtSair;
    private javax.swing.JComboBox<String> CbEscolaridade;
    private javax.swing.JComboBox<String> CbEstado;
    private javax.swing.JComboBox<String> CbEstadoCivil;
    private javax.swing.JComboBox<String> CbSexo;
    private javax.swing.JFormattedTextField FtfCEP;
    private javax.swing.JFormattedTextField FtfCPF;
    private javax.swing.JFormattedTextField FtfCelular;
    private javax.swing.JFormattedTextField FtfDataNascto;
    private javax.swing.JFormattedTextField FtfRG;
    private javax.swing.JFormattedTextField FtfTelRes;
    private javax.swing.JLabel LbBairro;
    private javax.swing.JLabel LbCEP;
    private javax.swing.JLabel LbCPF;
    private javax.swing.JLabel LbCelular;
    private javax.swing.JLabel LbCidade;
    private javax.swing.JLabel LbDataNascto;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbEscolaridade;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbEstadoCivil;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbNumero;
    private javax.swing.JLabel LbRG;
    private javax.swing.JLabel LbSexo;
    private javax.swing.JLabel LbTelRes;
    private javax.swing.JTextField TfBairro;
    private javax.swing.JTextField TfCidade;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfNome;
    private javax.swing.JTextField TfNumero;
    // End of variables declaration//GEN-END:variables
    private DaoAluno daoAluno = null;
    private Aluno aluno = null;
    private Conexao conexao = null;
}