/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoInstrutor;
import fatec.poo.model.Instrutor;
import javax.swing.JOptionPane;

/**
 *
 * @author CHRISTIANRODRIGOCORR
 */
public class GuiInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GuiInstrutor
     */
    public GuiInstrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfNumero = new javax.swing.JTextField();
        LbNumero = new javax.swing.JLabel();
        LbEstadoCivil = new javax.swing.JLabel();
        LbEndereco = new javax.swing.JLabel();
        LbCEP = new javax.swing.JLabel();
        TfEndereco = new javax.swing.JTextField();
        LbTelRes = new javax.swing.JLabel();
        LbCelular = new javax.swing.JLabel();
        LbDataNascto = new javax.swing.JLabel();
        LbBairro = new javax.swing.JLabel();
        TfBairro = new javax.swing.JTextField();
        LbCidade = new javax.swing.JLabel();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        TfCidade = new javax.swing.JTextField();
        LbRG = new javax.swing.JLabel();
        BtInserir = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();
        LbEmail = new javax.swing.JLabel();
        BtConsultar = new javax.swing.JButton();
        TfEmail = new javax.swing.JTextField();
        LbCPF = new javax.swing.JLabel();
        LbEstado = new javax.swing.JLabel();
        CbEstado = new javax.swing.JComboBox<>();
        CbSexo = new javax.swing.JComboBox<>();
        LbNome = new javax.swing.JLabel();
        TfNome = new javax.swing.JTextField();
        LbSexo = new javax.swing.JLabel();
        CbEstadoCivil = new javax.swing.JComboBox<>();
        TfFormacao = new javax.swing.JTextField();
        LbFormacao = new javax.swing.JLabel();
        TfAreaDeAtuacao = new javax.swing.JTextField();
        LbAreadeAtuacai = new javax.swing.JLabel();
        FtfCPF = new javax.swing.JFormattedTextField();
        FtfCEP = new javax.swing.JFormattedTextField();
        FtfRG = new javax.swing.JFormattedTextField();
        FtfTelRes = new javax.swing.JFormattedTextField();
        FtfCelular = new javax.swing.JFormattedTextField();
        FtfDataNascto = new javax.swing.JFormattedTextField();

        setTitle("Cadastrar Instrutor");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TfNumero.setEnabled(false);

        LbNumero.setText("Nº");
        LbNumero.setEnabled(false);

        LbEstadoCivil.setText("Estado Civil");
        LbEstadoCivil.setEnabled(false);

        LbEndereco.setText("Endereço");
        LbEndereco.setEnabled(false);

        LbCEP.setText("CEP");
        LbCEP.setEnabled(false);

        TfEndereco.setEnabled(false);

        LbTelRes.setText("Tel. Res");
        LbTelRes.setEnabled(false);

        LbCelular.setText("Celular");
        LbCelular.setEnabled(false);

        LbDataNascto.setText("Data Nascto");
        LbDataNascto.setEnabled(false);

        LbBairro.setText("Bairro");
        LbBairro.setEnabled(false);

        TfBairro.setEnabled(false);

        LbCidade.setText("Cidade");
        LbCidade.setEnabled(false);

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.setEnabled(false);
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.setEnabled(false);
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        TfCidade.setEnabled(false);

        LbRG.setText("RG");
        LbRG.setEnabled(false);

        BtInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        BtInserir.setText("Inserir");
        BtInserir.setEnabled(false);
        BtInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInserirActionPerformed(evt);
            }
        });

        BtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        BtSair.setText("Sair");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        LbEmail.setText("Email");
        LbEmail.setEnabled(false);

        BtConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        BtConsultar.setText("Consultar");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        TfEmail.setEnabled(false);

        LbCPF.setText("CPF");
        LbCPF.setEnabled(false);

        LbEstado.setText("Estado");
        LbEstado.setEnabled(false);

        CbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        CbEstado.setSelectedIndex(-1);
        CbEstado.setEnabled(false);

        CbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        CbSexo.setSelectedIndex(-1);
        CbSexo.setEnabled(false);

        LbNome.setText("Nome");
        LbNome.setEnabled(false);

        TfNome.setEnabled(false);

        LbSexo.setText("Sexo");
        LbSexo.setEnabled(false);

        CbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado" }));
        CbEstadoCivil.setSelectedIndex(-1);
        CbEstadoCivil.setEnabled(false);

        TfFormacao.setEnabled(false);

        LbFormacao.setText("Formação");
        LbFormacao.setEnabled(false);

        TfAreaDeAtuacao.setEnabled(false);

        LbAreadeAtuacai.setText("Àrea de Atuação");
        LbAreadeAtuacai.setEnabled(false);

        try {
            FtfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FtfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfCEP.setEnabled(false);

        try {
            FtfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfRG.setEnabled(false);

        try {
            FtfTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfTelRes.setEnabled(false);

        try {
            FtfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfCelular.setEnabled(false);

        try {
            FtfDataNascto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtfDataNascto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbNome)
                    .addComponent(LbSexo)
                    .addComponent(LbEndereco)
                    .addComponent(LbBairro)
                    .addComponent(LbRG)
                    .addComponent(LbCidade)
                    .addComponent(LbEmail)
                    .addComponent(LbFormacao)
                    .addComponent(LbCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FtfCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(TfFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(LbAreadeAtuacai)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TfAreaDeAtuacao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(FtfRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(TfCidade, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addComponent(LbEstado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LbCEP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LbTelRes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FtfTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbCelular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LbNumero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LbDataNascto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FtfDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LbEstadoCivil)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfDataNascto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEndereco)
                    .addComponent(LbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbBairro)
                    .addComponent(LbCEP)
                    .addComponent(FtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCidade)
                    .addComponent(LbTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRG)
                    .addComponent(LbCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbFormacao)
                    .addComponent(TfAreaDeAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbAreadeAtuacai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LbEmail)
                    .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtInserir)
                    .addComponent(BtConsultar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir)
                    .addComponent(BtSair))
                .addGap(30, 30, 30))
        );

        TfEndereco.getAccessibleContext().setAccessibleName("Endereço");
        TfBairro.getAccessibleContext().setAccessibleName("Bairro");
        BtAlterar.getAccessibleContext().setAccessibleName("Botão Alterar");
        BtExcluir.getAccessibleContext().setAccessibleName("Botão Excluir");
        TfCidade.getAccessibleContext().setAccessibleName("Cidade");
        BtInserir.getAccessibleContext().setAccessibleName("Botão Inserir");
        BtSair.getAccessibleContext().setAccessibleName("Botão Sair");
        BtConsultar.getAccessibleContext().setAccessibleName("Botão Consultar");
        CbSexo.getAccessibleContext().setAccessibleName("Sexo");
        TfNome.getAccessibleContext().setAccessibleName("Nome");
        TfFormacao.getAccessibleContext().setAccessibleName("Formação");
        FtfCPF.getAccessibleContext().setAccessibleName("CPF");
        FtfRG.getAccessibleContext().setAccessibleName("RG");
        FtfDataNascto.getAccessibleContext().setAccessibleName("Data de Nascimento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        instrutor = null;
        instrutor = daoInstrutor.consultar(FtfCPF.getText());
        if (instrutor == null) {
            FtfCPF.setEnabled(false);
            CbSexo.setEnabled(true);
            CbEstadoCivil.setEnabled(true);
            TfFormacao.setEnabled(true);
            CbEstado.setEnabled(true);
            FtfDataNascto.setEnabled(true);
            FtfCEP.setEnabled(true);
            FtfTelRes.setEnabled(true);
            FtfRG.setEnabled(true);
            FtfCelular.setEnabled(true);
            TfNome.setEnabled(true);
            TfEndereco.setEnabled(true);
            TfNumero.setEnabled(true);
            TfBairro.setEnabled(true);
            TfCidade.setEnabled(true);
            TfEmail.setEnabled(true);
            TfAreaDeAtuacao.setEnabled(true);
                       
            BtConsultar.setEnabled(false);
            BtInserir.setEnabled(true);
            BtAlterar.setEnabled(false);
            BtExcluir.setEnabled(false);
            
            TfNome.requestFocus();
        } else {
            CbSexo.setSelectedItem(instrutor.getSexo());
            CbEstadoCivil.setSelectedItem(instrutor.getEstadoCivil());
            TfFormacao.setText(instrutor.getFormacao());
            CbEstado.setSelectedItem(instrutor.getEstado());
            FtfDataNascto.setText(instrutor.getDataNasc());
            FtfCEP.setText(instrutor.getCEP());
            FtfTelRes.setText(instrutor.getTelefone());
            FtfRG.setText(instrutor.getRG());
            FtfCelular.setText(instrutor.getCelular());
            TfNome.setText(instrutor.getNome());
            TfEndereco.setText(instrutor.getEndereco());
            TfNumero.setText(Integer.toString(instrutor.getNumero()));
            TfBairro.setText(instrutor.getBairro());
            TfCidade.setText(instrutor.getCidade());
            TfEmail.setText(instrutor.getEmail());
            TfAreaDeAtuacao.setText(instrutor.getAreaAtuacao());
            
            FtfCPF.setEnabled(false); 
            CbSexo.setEnabled(true);
            CbEstadoCivil.setEnabled(true);
            TfFormacao.setEnabled(true);
            CbEstado.setEnabled(true);
            FtfDataNascto.setEnabled(true);
            FtfCEP.setEnabled(true);
            FtfTelRes.setEnabled(true);
            FtfRG.setEnabled(true);
            FtfCelular.setEnabled(true);
            TfNome.setEnabled(true);        
            TfEndereco.setEnabled(true);
            TfNumero.setEnabled(true);
            TfBairro.setEnabled(true);
            TfCidade.setEnabled(true);
            TfEmail.setEnabled(true);
            TfAreaDeAtuacao.setEnabled(true);

            BtConsultar.setEnabled(false);
            BtInserir.setEnabled(false);
            BtAlterar.setEnabled(true);
            BtExcluir.setEnabled(true);
            
            TfNome.requestFocus(); 
        }
    }//GEN-LAST:event_BtConsultarActionPerformed

    private void BtInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInserirActionPerformed
        instrutor = new Instrutor(TfNome.getText(), FtfCPF.getText());
        
        instrutor.setSexo(String.valueOf(CbSexo.getSelectedItem()));
        instrutor.setEstadoCivil(String.valueOf(CbEstadoCivil.getSelectedItem()));
        instrutor.setFormacao(String.valueOf(TfFormacao.getText()));
        instrutor.setEstado(String.valueOf(CbEstado.getSelectedItem()));
        instrutor.setDataNasc(FtfDataNascto.getText());
        instrutor.setCEP(FtfCEP.getText());
        instrutor.setTelefone(FtfTelRes.getText());
        instrutor.setRG(FtfRG.getText());
        instrutor.setCelular(FtfCelular.getText());
        instrutor.setEndereco(TfEndereco.getText());
        instrutor.setNumero(Integer.valueOf(TfNumero.getText()));
        instrutor.setBairro(TfBairro.getText());
        instrutor.setCidade(TfCidade.getText());
        instrutor.setEmail(TfEmail.getText());
        instrutor.setAreaAtuacao(TfAreaDeAtuacao.getText());        
        
        daoInstrutor.inserir(instrutor);
        
        FtfCPF.setText("");
        CbSexo.setSelectedItem(-1);
        CbEstadoCivil.setSelectedItem(-1);
        TfFormacao.setText("");
        CbEstado.setSelectedItem(-1);
        FtfDataNascto.setText("");
        FtfCEP.setText("");
        FtfTelRes.setText("");
        FtfRG.setText("");
        FtfCelular.setText("");
        TfNome.setText("");
        TfEndereco.setText("");
        TfNumero.setText("");
        TfBairro.setText("");
        TfCidade.setText("");
        TfEmail.setText("");
        TfAreaDeAtuacao.setText("");
        
        
        FtfCPF.setEnabled(true);
        CbSexo.setEnabled(false);
        CbEstadoCivil.setEnabled(false);
        TfFormacao.setEnabled(false);
        CbEstado.setEnabled(false); 
        FtfDataNascto.setEnabled(false);
        FtfCEP.setEnabled(false);
        FtfTelRes.setEnabled(false);
        FtfRG.setEnabled(false);
        FtfCelular.setEnabled(false);
        TfNome.setEnabled(false);        
        TfEndereco.setEnabled(false);
        TfNumero.setEnabled(false);
        TfBairro.setEnabled(false);
        TfCidade.setEnabled(false);
        TfEmail.setEnabled(false);
        TfAreaDeAtuacao.setEnabled(false);
        
        BtConsultar.setEnabled(true);
        BtInserir.setEnabled(false);
        
        FtfCPF.requestFocus();
    }//GEN-LAST:event_BtInserirActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0) {
            instrutor.setNome(TfNome.getText());
            instrutor.setSexo(String.valueOf(CbSexo.getSelectedItem()));
            instrutor.setEstadoCivil(String.valueOf(CbEstadoCivil.getSelectedItem()));
            instrutor.setFormacao(String.valueOf(TfFormacao.getText()));
            instrutor.setEstado(String.valueOf(CbEstado.getSelectedItem()));
            instrutor.setDataNasc(FtfDataNascto.getText());
            instrutor.setCEP(FtfCEP.getText());
            instrutor.setTelefone(FtfTelRes.getText());
            instrutor.setRG(FtfRG.getText());
            instrutor.setCelular(FtfCelular.getText());
            instrutor.setEndereco(TfEndereco.getText());
            instrutor.setNumero(Integer.valueOf(TfNumero.getText()));
            instrutor.setBairro(TfBairro.getText());
            instrutor.setCidade(TfCidade.getText());
            instrutor.setEmail(TfEmail.getText());
            instrutor.setAreaAtuacao(TfAreaDeAtuacao.getText());
            daoInstrutor.alterar(instrutor);
        } 
        
        FtfCPF.setText("");
        CbSexo.setSelectedItem(-1);
        CbEstadoCivil.setSelectedItem(-1);
        TfFormacao.setText("");
        CbEstado.setSelectedItem(-1);
        FtfDataNascto.setText("");
        FtfCEP.setText("");
        FtfTelRes.setText("");
        FtfRG.setText("");
        FtfCelular.setText("");
        TfNome.setText("");
        TfEndereco.setText("");
        TfNumero.setText("");
        TfBairro.setText("");
        TfCidade.setText("");
        TfEmail.setText("");
        TfAreaDeAtuacao.setText("");
        
        FtfCPF.setEnabled(true);
        CbSexo.setEnabled(false);
        CbEstadoCivil.setEnabled(false);
        TfFormacao.setEnabled(false);
        CbEstado.setEnabled(false); 
        FtfDataNascto.setEnabled(false);
        FtfCEP.setEnabled(false);
        FtfTelRes.setEnabled(false);
        FtfRG.setEnabled(false);
        FtfCelular.setEnabled(false);
        TfNome.setEnabled(false);        
        TfEndereco.setEnabled(false);
        TfNumero.setEnabled(false);
        TfBairro.setEnabled(false);
        TfCidade.setEnabled(false);
        TfEmail.setEnabled(false);
        TfAreaDeAtuacao.setEnabled(false);
        
        BtConsultar.setEnabled(true);
        BtInserir.setEnabled(false);
        BtAlterar.setEnabled(false);
        BtExcluir.setEnabled(false);
        
        FtfCPF.requestFocus();
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0){
            daoInstrutor.excluir(instrutor);

            FtfCPF.setText("");
            CbSexo.setSelectedItem(-1);
            CbEstadoCivil.setSelectedItem(-1);
            TfFormacao.setText("");
            CbEstado.setSelectedItem(-1);
            FtfDataNascto.setText("");
            FtfCEP.setText("");
            FtfTelRes.setText("");
            FtfRG.setText("");
            FtfCelular.setText("");
            TfNome.setText("");
            TfEndereco.setText("");
            TfNumero.setText("");
            TfBairro.setText("");
            TfCidade.setText("");
            TfEmail.setText("");
            TfAreaDeAtuacao.setText("");

            FtfCPF.setEnabled(true);
            CbSexo.setEnabled(false);
            CbEstadoCivil.setEnabled(false);
            TfFormacao.setEnabled(false);
            CbEstado.setEnabled(false); 
            FtfDataNascto.setEnabled(false);
            FtfCEP.setEnabled(false);
            FtfTelRes.setEnabled(false);
            FtfRG.setEnabled(false);
            FtfCelular.setEnabled(false);
            TfNome.setEnabled(false);        
            TfEndereco.setEnabled(false);
            TfNumero.setEnabled(false);
            TfBairro.setEnabled(false);
            TfCidade.setEnabled(false);
            TfEmail.setEnabled(false);
            TfAreaDeAtuacao.setEnabled(false);

            BtConsultar.setEnabled(true);
            BtInserir.setEnabled(false);
            BtAlterar.setEnabled(false);
            BtExcluir.setEnabled(false);

            FtfCPF.requestFocus();
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        dispose();
    }//GEN-LAST:event_BtSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("chris","goku");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoInstrutor = new DaoInstrutor(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        conexao.fecharConexao();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtInserir;
    private javax.swing.JButton BtSair;
    private javax.swing.JComboBox<String> CbEstado;
    private javax.swing.JComboBox<String> CbEstadoCivil;
    private javax.swing.JComboBox<String> CbSexo;
    private javax.swing.JFormattedTextField FtfCEP;
    private javax.swing.JFormattedTextField FtfCPF;
    private javax.swing.JFormattedTextField FtfCelular;
    private javax.swing.JFormattedTextField FtfDataNascto;
    private javax.swing.JFormattedTextField FtfRG;
    private javax.swing.JFormattedTextField FtfTelRes;
    private javax.swing.JLabel LbAreadeAtuacai;
    private javax.swing.JLabel LbBairro;
    private javax.swing.JLabel LbCEP;
    private javax.swing.JLabel LbCPF;
    private javax.swing.JLabel LbCelular;
    private javax.swing.JLabel LbCidade;
    private javax.swing.JLabel LbDataNascto;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbEndereco;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbEstadoCivil;
    private javax.swing.JLabel LbFormacao;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbNumero;
    private javax.swing.JLabel LbRG;
    private javax.swing.JLabel LbSexo;
    private javax.swing.JLabel LbTelRes;
    private javax.swing.JTextField TfAreaDeAtuacao;
    private javax.swing.JTextField TfBairro;
    private javax.swing.JTextField TfCidade;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfEndereco;
    private javax.swing.JTextField TfFormacao;
    private javax.swing.JTextField TfNome;
    private javax.swing.JTextField TfNumero;
    // End of variables declaration//GEN-END:variables
    private DaoInstrutor daoInstrutor = null;
    private Instrutor instrutor = null;
    private Conexao conexao = null;
}
