/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author CHRISTIANRODRIGOCORR
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        BtCadastCurso = new javax.swing.JMenuItem();
        BtCadastTurma = new javax.swing.JMenuItem();
        BtCadastrarInstrutor = new javax.swing.JMenuItem();
        BtCadastrarAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        BtSair = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        BtAlocInstrutor = new javax.swing.JMenuItem();
        BtEfeturarMatricula = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");
        setName("FrameMenuPrincipal"); // NOI18N

        jMenu7.setText("Cadastros");

        BtCadastCurso.setText("Curso");
        BtCadastCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastCursoActionPerformed(evt);
            }
        });
        jMenu7.add(BtCadastCurso);

        BtCadastTurma.setText("Turma");
        BtCadastTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastTurmaActionPerformed(evt);
            }
        });
        jMenu7.add(BtCadastTurma);

        BtCadastrarInstrutor.setText("Instrutor");
        BtCadastrarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarInstrutorActionPerformed(evt);
            }
        });
        jMenu7.add(BtCadastrarInstrutor);

        BtCadastrarAluno.setText("Aluno");
        BtCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenu7.add(BtCadastrarAluno);
        jMenu7.add(jSeparator1);

        BtSair.setText("Sair");
        BtSair.setName("Sair"); // NOI18N
        jMenu7.add(BtSair);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Operações");
        jMenu8.setName("Operacoes"); // NOI18N

        BtAlocInstrutor.setText("Alocar Instrutor");
        BtAlocInstrutor.setName("BtAlocInstrutor"); // NOI18N
        BtAlocInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlocInstrutorActionPerformed(evt);
            }
        });
        jMenu8.add(BtAlocInstrutor);

        BtEfeturarMatricula.setText("Efeturar Matrícula");
        BtEfeturarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEfeturarMatriculaActionPerformed(evt);
            }
        });
        jMenu8.add(BtEfeturarMatricula);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadastCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCadastCursoActionPerformed

    private void BtCadastrarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCadastrarInstrutorActionPerformed

    private void BtEfeturarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEfeturarMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtEfeturarMatriculaActionPerformed

    private void BtAlocInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlocInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtAlocInstrutorActionPerformed

    private void BtCadastTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCadastTurmaActionPerformed

    private void BtCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtCadastrarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtAlocInstrutor;
    private javax.swing.JMenuItem BtCadastCurso;
    private javax.swing.JMenuItem BtCadastTurma;
    private javax.swing.JMenuItem BtCadastrarAluno;
    private javax.swing.JMenuItem BtCadastrarInstrutor;
    private javax.swing.JMenuItem BtEfeturarMatricula;
    private javax.swing.JMenuItem BtSair;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
