/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author CHRISTIANRODRIGOCORR
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuItemCadastCurso = new javax.swing.JMenuItem();
        MenuItemCadastTurma = new javax.swing.JMenuItem();
        MenuItemCadastrarInstrutor = new javax.swing.JMenuItem();
        MenuItemCadastrarAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemSair = new javax.swing.JMenuItem();
        MenuOperacoes = new javax.swing.JMenu();
        MenuItemAlocInstrutor = new javax.swing.JMenuItem();
        MenuItemEfeturarMatricula = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");
        setName("FrameMenuPrincipal"); // NOI18N

        MenuCadastros.setText("Cadastros");

        MenuItemCadastCurso.setText("Curso");
        MenuItemCadastCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastCursoActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemCadastCurso);

        MenuItemCadastTurma.setText("Turma");
        MenuItemCadastTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastTurmaActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemCadastTurma);

        MenuItemCadastrarInstrutor.setText("Instrutor");
        MenuItemCadastrarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastrarInstrutorActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemCadastrarInstrutor);

        MenuItemCadastrarAluno.setText("Aluno");
        MenuItemCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastrarAlunoActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemCadastrarAluno);
        MenuCadastros.add(jSeparator1);

        MenuItemSair.setText("Sair");
        MenuItemSair.setName("Sair"); // NOI18N
        MenuCadastros.add(MenuItemSair);

        MenuPrincipal.add(MenuCadastros);

        MenuOperacoes.setText("Operações");
        MenuOperacoes.setName("Operacoes"); // NOI18N

        MenuItemAlocInstrutor.setText("Alocar Instrutor");
        MenuItemAlocInstrutor.setName("MenuItemAlocInstrutor"); // NOI18N
        MenuItemAlocInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAlocInstrutorActionPerformed(evt);
            }
        });
        MenuOperacoes.add(MenuItemAlocInstrutor);

        MenuItemEfeturarMatricula.setText("Efeturar Matrícula");
        MenuItemEfeturarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEfeturarMatriculaActionPerformed(evt);
            }
        });
        MenuOperacoes.add(MenuItemEfeturarMatricula);

        MenuPrincipal.add(MenuOperacoes);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCadastCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCadastCursoActionPerformed

    private void MenuItemCadastrarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastrarInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCadastrarInstrutorActionPerformed

    private void MenuItemEfeturarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEfeturarMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemEfeturarMatriculaActionPerformed

    private void MenuItemAlocInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAlocInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemAlocInstrutorActionPerformed

    private void MenuItemCadastTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCadastTurmaActionPerformed

    private void MenuItemCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastrarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemCadastrarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenuItem MenuItemAlocInstrutor;
    private javax.swing.JMenuItem MenuItemCadastCurso;
    private javax.swing.JMenuItem MenuItemCadastTurma;
    private javax.swing.JMenuItem MenuItemCadastrarAluno;
    private javax.swing.JMenuItem MenuItemCadastrarInstrutor;
    private javax.swing.JMenuItem MenuItemEfeturarMatricula;
    private javax.swing.JMenuItem MenuItemSair;
    private javax.swing.JMenu MenuOperacoes;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
